config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'welcome/identification', to: 'welcome#identification'
  post 'welcome/user', to: 'welcome#show'
  get 'welcome/:user', to: 'welcome#personal_page'
  get '/accueil', to: 'welcome#accueil'
  post '/accueil/:id', to: 'welcome#gossip'
  post '/accueil/:id/:userid', to: 'welcome#user'
  get '/contact', to: 'staff#contact'
  get '/team', to: 'staff#team'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tag_gossips
  has_many :tags, through: :tag_gossips
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  #belongs_to :sender, class_name: "User"
  #belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_gossips
  has_many :gossips, through: :tag_gossips
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city, optional: true
  has_many :gossips
  #has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  #has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def accueil

  end
end

app/controllers/staff_controller.rb
class StaffController < ApplicationController
  def contact

  end

  def team

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def identification
  end

  def show
    user = User.create(first_name: params["user_first_name"], last_name: params["user_last_name"])
    @current_user = user
    params["user"] = @current_user.first_name
  end

  def personal_page
    @current_user = User.last
    params["user"] = @current_user.first_name
  end

  def accueil
  end

  def gossip
    index = params["print"]
    @goss = Gossip.find(index)
  end

  def user
    id = params["name"]
    @us = User.find(id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Gossip Project</title>
  </head>
  <body>

    <section class="jumbotron text-center mb-0">
      <div class="container mt-5 mt-md-4 mt-lg-3 pt-5 pt-md-4 pt-lg-3" id="jumjum">
        <div class="row justify-content-md-center">
          <div class="col-sm-6 col-sm-offset-3 mb-3">
            <div class="card">
              <div class="card-body">
                <p class="card-text">
                  <h1 class="police mt-4">Bienvenue</h1>
                  <h2 class="police mt-4">sur The Gossip Project</h2>
                  <h4 class="police mt-4"><a href="welcome/identification"><button class="btn btn-primary"type="button" name="button">Connexion</button></a></h4>
                </div>
              </div>
            </div>
          </div>
        </div>
    </section>





  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="/">The Gossip Project</a>
        <button class="navbar-toggler" type="button" name="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" <%= link_to "Welcome", welcome_user_path %><span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" <%= link_to "Accueil", accueil_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" <%= link_to "La team", team_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" <%= link_to "Contact", contact_path %></a>
            </li>
          </ul>
        </div>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/staff/contact.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Contact</title>
  </head>
  <body>
    <section class="container">
      <div class="row mt-5 mb-3">
        <div class="col">
          <h1 class="text-center">Contacter l'equipe</h1>
        </div>
      </div>
      <div class="card-deck">
        <div class="card">
          <div class="card-body">
            <p class="card-text">
              <h3 class="text-center border-bottom pb-4 mb-4">To contact me : </h3>
              <B>first_name :</B> <%= User  .first_name %><br>
              <B>last name :</B> <%= User.first.last_name %><br>
              <B>email :</B> <%= User.first.email %><br>
              <B>age :</B> <%= User.first.age %><br>
              <B>city :</B> <%= User.first.city.name %><br>
              <B>description :</B> <%= User.first.description %>
            </p>
            <small class="text-muted">Lucas, Octobre 2019</small>
          </div>
        </div>
        </div>
      </section>
  </body>
</html>

app/views/staff/team.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Team</title>
  </head>
  <body>
    <section class="container">
    <div class="row mt-5 mb-3">
      <div class="col">
        <h1 class="text-center">Voici la super team qui a produit ce site</h1>
      </div>
    </div>
    <div class="card-deck">
      <div class="card">
        <img class="card-img-top" <%= image_tag "yoda.jpg"%>
        <div class="card-body">
          <p class="card-text">
            Bonnes relations avec les Wookies, j’entretiens.
          </p>
          <small class="text-muted">Yoda, Octobre 2019</small>
        </div>
      </div>
        <div class="card">
          <img class="card-img-top" <%= image_tag "chewbi.jpg"%>
          <div class="card-body">
            <p class="card-text">
              Rrwwgawwrrggawwrr
            </p>
            <small class="text-muted">chewbi, Avril 2019</small>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/welcome/accueil.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <section class="container">
    <div class="row mt-5 mb-3">
      <div class="col">
        <h1 class="text-center">Bonjour</h1>
        <br><br>
        <h2 class="text-center">Voici tous les gossips, n'hesite pas a les lire :)</h2>
      </div>
    </div>

      <% Gossip.all.each_with_index do |gossip, index| %>
      <div class="card-deck">
      <div class="card mb-3">
        <div class="card-body">
          <p class="card-text">
            <%= gossip.content %><br/>
          </p>
          <small class="text-muted"><%= gossip.user.first_name %></small>
          <form action="/accueil/<%=index+1%>" method="post">
            <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
            <button type="submit" class="btn btn-primary" name="print" value="<%=index+1%>">Show</button>
          </form>
        </div>
      </div>
      </div>
      <%end%>


  </section>
  </body>
</html>

app/views/welcome/gossip.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <section class="container">
      <div class="row mt-5 mb-3">
        <div class="col">
          <h1 class="text-center">Voici le gossip</h1>
          <br><br>
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-body">
          <p class="card-text">
            <h2><%= @goss.user.first_name %></h2>
            <h4><%= @goss.content %></h4>
          </p>
          <br><br>
          <p>Plus d'infos sur l'auteur ?</p>
          <form action="/accueil/<%=@goss.id%>/<%=@goss.user.id%>" method="post">
            <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
            <button type="submit" class="btn btn-primary" name="name" value="<%=@goss.user.id%>">Author</button>
          </form>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/welcome/identification.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Welcome</title>
  </head>
  <body>
    <section class="container">
      <div class="row mt-5 mb-3">
        <div class="col">
          <h1 class="text-center">Bienvenue sur ce super site !</h1>
          <br><br>
          <h2 class="text-center">JE t'invite à te connecter pour une meilleure expérience :)</h2>
          <br>
        </div>
      </div>
      <form action="/welcome/user" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <div class="form-group">
          <label for="input_first">Entre ton prénom</label>
          <input type="text" name="user_first_name" class="form-control" id="input_first" placeholder="Enter first_name">
        </div>
        <div class="form-group">
          <label for="input_last">Entre ton nom</label>
          <input type="text" name="user_last_name" class="form-control" id="input_last" placeholder="Enter last_name">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </section>
  </body>
</html>

app/views/welcome/personal_page.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <section class="container">
    <div class="row mt-5 mb-3">
      <div class="col">
        <h1 class="text-center">Bienvenue sur ce super site <%= @current_user.first_name %> </h1>
          <img class="card-img-top" <%= image_tag "image.gif"%>
      </div>
    </div>
  </section>
  </body>
</html>

app/views/welcome/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <section class="container">
    <div class="row mt-5 mb-3">
      <div class="col">
        <h1 class="text-center">Bienvenue sur ce super site <%= @current_user.first_name %> </h1>
        <img class="card-img-top" <%= image_tag "image.gif"%>
      </div>
    </div>
  </section>
  </body>
</html>

app/views/welcome/user.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>User</title>
  </head>
  <body>
    <section class="container">
      <div class="row mt-5 mb-3">
        <div class="col">
          <h1 class="text-center">Voici les informations de l'auteur</h1>
          <br>
          <div class="card mb-3">
            <div class="card-body">
              <p class="card-text">
                <B>Prénom</B> : <%= @us.first_name %><br><br>
                <B>Nom</B> : <%= @us.last_name %><br><br>
                <B>email</B> : <%= @us.email %><br><br>
                <B>age</B> : <%= @us.age %><br><br>
                <B>description</B> : <%= @us.description %>
              </p>
            </div>
          </div>
        </div>
      </div>
  </body>
</html>